In [4]:
#2) Crear un vector de ceros de tamaño 10
import numpy as np

array= np.zeros([10])

array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
print (array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
array[5]=1

In [7]:
print(array)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [8]:
#4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc

array_orden= np.arange(50)

print(array_orden)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [11]:
array_cambiar_orden= array_orden[::-1]

In [12]:
print(array_cambiar_orden)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [21]:
# 5) Crear una matriz de 3 x 3 con valores del cero al 8

matriz= np.random.randint(0, 8, 9)
print(matriz)
matriz3=matriz.reshape(3,3)
matriz3


[6 4 1 5 5 3 7 3 7]


array([[6, 4, 1],
       [5, 5, 3],
       [7, 3, 7]])

In [32]:
#6) Encontrar los indices que no sean cero en un arreglo
arreglo = np.array([1, 2, 0, 0, 4, 0])

print(arreglo)

arreglo > 0

################3


[1 2 0 0 4 0]


array([ True,  True, False, False,  True, False])

In [30]:
#7) Crear una matriz de identidad 3 x 3
matriz_identidad=np.eye(3,3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
#8) Crear una matriz 3 x 3 x 3 con valores randomicos

matriz_dimensiones= np.arange(27)

print(matriz_dimensiones)

matriz_tres= matriz_dimensiones.reshape(3,3,3)

print(matriz_tres)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [55]:
#9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

matriz_dimension= np.arange(5,105,1)

print(matriz_dimension)

matriz_diez= matriz_dimension.reshape(10,10)

print(matriz_diez)

print('Menor')
print(matriz_diez.min())
print('Mayor')
print(matriz_diez.max())



[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104]
[[  5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54]
 [ 55  56  57  58  59  60  61  62  63  64]
 [ 65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91  92  93  94]
 [ 95  96  97  98  99 100 101 102 103 104]]
Menor
5
Mayor
104


In [ ]:
#10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

