In [6]:
#pip install numpy
import numpy as np

print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))


<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
np.zeros([1])

array([0.])

In [9]:
np.zeros((1))

array([0.])

In [10]:
np.zeros([5,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.zeros((5,7,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(4,20) # [4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(-12)

array([], dtype=int32)

In [20]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.arange(-12,0, 0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5])

In [23]:
arreglo_pares= np.arange(0,20,2)

print(arreglo_pares.size)
print(len(arreglo_pares))


10
10


In [26]:
arreglo_tes_dimensiones= np.zeros((2,3,4))
print(arreglo_tes_dimensiones.shape)

(2, 3, 4)


In [27]:
arreglo_pares.shape


(10,)

In [30]:
arreglo_pares.reshape(5,2)


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [29]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [33]:
arreglo_24= np.arange(24)

In [34]:
print(arreglo_24)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [35]:
arreglo_24.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [36]:
arreglo_24.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [38]:
arreglo_24.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
arreglo_24.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [40]:
arreglo_24.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [41]:
arreglo_24.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [42]:
arreglo_24.reshape(4,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [46]:
a= np.array([10,10,10])
b= np.array([5,5,5])


In [47]:
#suma
a+ b

array([15, 15, 15])

In [48]:
#resta
a - b

array([5, 5, 5])

In [49]:
#multiplicacion
a *b


array([50, 50, 50])

In [50]:
#division
a/b

array([2., 2., 2.])

In [64]:
#arreglo 3 dimenciones 

arreglo_dimensiones= np.arange(-40,40,3)

print(arreglo_dimensiones.size)

c= arreglo_dimensiones.reshape(3,3,3)

d= arreglo_dimensiones.reshape(3,3,3)

27


In [66]:
print(arreglo_dimensiones)
print(c)
print(d)

[-40 -37 -34 -31 -28 -25 -22 -19 -16 -13 -10  -7  -4  -1   2   5   8  11
  14  17  20  23  26  29  32  35  38]
[[[-40 -37 -34]
  [-31 -28 -25]
  [-22 -19 -16]]

 [[-13 -10  -7]
  [ -4  -1   2]
  [  5   8  11]]

 [[ 14  17  20]
  [ 23  26  29]
  [ 32  35  38]]]
[[[-40 -37 -34]
  [-31 -28 -25]
  [-22 -19 -16]]

 [[-13 -10  -7]
  [ -4  -1   2]
  [  5   8  11]]

 [[ 14  17  20]
  [ 23  26  29]
  [ 32  35  38]]]


In [67]:
c + d


array([[[-80, -74, -68],
        [-62, -56, -50],
        [-44, -38, -32]],

       [[-26, -20, -14],
        [ -8,  -2,   4],
        [ 10,  16,  22]],

       [[ 28,  34,  40],
        [ 46,  52,  58],
        [ 64,  70,  76]]])

In [68]:
c -d


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [69]:
c * d

array([[[1600, 1369, 1156],
        [ 961,  784,  625],
        [ 484,  361,  256]],

       [[ 169,  100,   49],
        [  16,    1,    4],
        [  25,   64,  121]],

       [[ 196,  289,  400],
        [ 529,  676,  841],
        [1024, 1225, 1444]]])

In [70]:
c/ d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [71]:
#modulo

a % b

array([0, 0, 0], dtype=int32)

In [73]:
#multiplicacion
print(a * 10)
#sumar
print(a + 10)
#restar
print(a - 10)
#dividir
print(a / 10)
#mod
print(a % 3)


[100 100 100]
[20 20 20]
[0 0 0]
[1. 1. 1.]
[1 1 1]


In [77]:
arreglo_muestra = np.arange(20).reshape(5,2,2)


In [78]:
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [79]:
resp = arreglo_muestra > 5 

In [80]:
resp

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [81]:
resp = arreglo_muestra[resp]

In [82]:
resp

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [94]:
#mayores a 5 y menores 12

resp2= (arreglo_muestra > 5) & (arreglo_muestra < 12)

In [95]:
resp2

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [96]:
resp2 = arreglo_muestra[resp2]

In [97]:
resp2

array([ 6,  7,  8,  9, 10, 11])

In [98]:
#mayores a 6 menores a 14 y pares

arreglo_muestra % 2




array([[[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]]], dtype=int32)

In [100]:
resp3= (arreglo_muestra > 6) & (arreglo_muestra < 14) & ((arreglo_muestra % 2) == 0)


In [101]:
resp3

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[ True, False],
        [ True, False]],

       [[ True, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [102]:
resp3 = arreglo_muestra[resp3]

In [103]:
resp3


array([ 8, 10, 12])

In [105]:
print(arreglo_muestra)
print('mayores a 6 menores a 14 y pares')
print(resp3)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
mayores a 6 menores a 14 y pares
[ 8 10 12]


In [106]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [108]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [109]:
#PRODUCTO punto
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [110]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [111]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [112]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [113]:
arreglo_doce.sum()

66

In [114]:
arreglo_doce.min()

0

In [115]:
arreglo_doce.max()

11

In [119]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [118]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [120]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [121]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])