In [5]:
import numpy as np

In [7]:
arreglo_0_a_90_grados= np.array([0,30,45,60,90])

In [9]:
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [19]:
radianes= arreglo_0_a_90_grados*np.pi/180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [20]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [21]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [22]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [23]:
arreglo_random= np.random.randint(11) #enteros positivos menos 1 contandole al cero

arreglo_random # [0,11[  enteros

10

In [24]:
arreglo_random1= np.random.randint(-1,2) #enteros positivos menos 1 contandole al cero

arreglo_random1 #[-1,2[

-1

In [25]:
arreglo_random2= np.random.randint(
    0, #minimo
    11, #maximo
    3) #numeo de randomicos

arreglo_random2

array([2, 4, 4])

In [26]:
arreglo_random2.mean()

3.3333333333333335

In [28]:
np.median(arreglo_random2)

4.0

In [29]:
np.std(arreglo_random2)

0.9428090415820634

In [30]:
np.var(arreglo_random2)

0.8888888888888888

In [31]:
np.mean(arreglo_random2)

3.3333333333333335